### ISSUE TITLE
Return actual errors

### ISSUE THREAD

**Issue by jjulian** [JasonCanCode/CRUDE-Futures#1]
When `network.response` is nil, it means there's an error with the url request.

Instead of returning an new generic error (`NSError(domain: "Unknown Error", code: 600, userInfo: nil)`) return the actual error that caused the problem (`return network.result`) <- I'm not sure that is exactly right, it needs to be tested.

In addition to the two places where `Alamofire.request` is called, the guard needs to be removed from `errorFromResponse()` too

**Comment by JasonCanCode** [comment]
Added an inspection of the `network.result.error` before generating a fallback error.
